version: "2"
services:
  master:
    image: "spark:2.0.2"
    network_mode: "bridge"
    command: "master"
    expose: 
      - "6066"
      - "7077"
      - "8080"
    ports:
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
  worker:
    image: "spark:2.0.2"
    network_mode: "bridge"
    links:
      - "master"
    command: "worker spark://master:7077"
    expose:
      - "8081"