version: "2"
services:
  namenode:
    image: "hdfs:2.7.3"
    container_name: "namenode"
    network_mode: "bridge"
    ports:
      - "9000:9000"
      - "50070:50070"
    volumes:
      - "$pwd/name:/hdfs/dfs/name"
    command:
      - ""
  datanode-1:
    image: "hdfs:2.7.3"
    container_name: "datanode1"
    network_mode: "bridge"
    links:
      - "namenode:hdfs"
    volumes:
      - "$pwd/data1:/hdfs/dfs/data"
    expose:
      - "50010"
      - "50020"
  datanode-2:
    image: "hdfs:2.7.3"
    container_name: "datanode2"
    network_mode: "bridge"
    links:
      - "namenode:hdfs"
    volumes:
      - "$pwd/data2:/hdfs/dfs/data"
    expose:
      - "50010"
      - "50020"